package Frontera;

public class DialogoOK extends javax.swing.JDialog {

    private int clickOk = 0;

    public DialogoOK(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void textoLabel(String texto) {
        textoLabel.setText(texto);
    }

    public void visible() {
        boolean val = true;
        this.setVisible(val);
        while (val == true) {
            if (clickOk == 1) {
                val = false;
            }
        }
        clickOk = 0;
        this.setVisible(val);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoPanel = new javax.swing.JPanel();
        textoLabel = new javax.swing.JLabel();
        ok = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dialogoPanel.setBackground(new java.awt.Color(36, 56, 63));
        dialogoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164, 186, 191)));
        dialogoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        textoLabel.setForeground(new java.awt.Color(164, 186, 191));
        textoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dialogoPanel.add(textoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 120));

        ok.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        ok.setForeground(new java.awt.Color(164, 186, 191));
        ok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ok.setText("OK");
        ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });
        dialogoPanel.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 40, 40));

        getContentPane().add(dialogoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked
        clickOk = 1;
        this.setVisible(false);
    }//GEN-LAST:event_okMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoOK dialog = new DialogoOK(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dialogoPanel;
    private javax.swing.JLabel ok;
    private javax.swing.JLabel textoLabel;
    // End of variables declaration//GEN-END:variables
}
