package Frontera;

import Control.ValidarRestaurante;
import DAO.RestauranteDAO;
import Entidad.Restaurante;

public class NuevoRestaurante extends javax.swing.JPanel {

    private final Restaurante restaurante = new Restaurante();
    private final ValidarRestaurante validar = new ValidarRestaurante();
    private final RestauranteDAO daoRes = new RestauranteDAO();

    private final DialogoOK dialogoOk = new DialogoOK(null, true);

    private int filaU;

    public NuevoRestaurante() {
        initComponents();
    }

    public boolean validarCampos() {
        return (nombreTF.getText().isEmpty() && ubicacionTF.getText().isEmpty() && tipoTF.getText().isEmpty() && horarioTF.getText().isEmpty());
    }

    public void vaciarCampos() {
        nombreTF.setText("");
        ubicacionTF.setText("");
        tipoTF.setText("");
        horarioTF.setText("");
    }

    public void guardarDatos() {

        restaurante.setNombre(nombreTF.getText());
        restaurante.setUbicacion(ubicacionTF.getText());
        restaurante.setTipo(tipoTF.getText());
        restaurante.setHorario(horarioTF.getText());

        String respuesta = validar.validarRestaurante(restaurante);

        if ("Longitud nombre incorrecta".equals(respuesta)) {
            dialogoOk.textoLabel(respuesta);
            dialogoOk.visible();
        } else if ("Longitud ubicación incorrecta".equals(respuesta)) {
            dialogoOk.textoLabel(respuesta);
            dialogoOk.visible();
        } else if ("Longitud tipo incorrecta".equals(respuesta)) {
            dialogoOk.textoLabel(respuesta);
            dialogoOk.visible();
        } else if ("Longitud horario incorrecta".equals(respuesta)) {
            dialogoOk.textoLabel(respuesta);
            dialogoOk.visible();
        } else {
            daoRes.crear(restaurante.getNombre(), ubicacionTF.getText(), tipoTF.getText(), horarioTF.getText());
            vaciarCampos();
            dialogoOk.textoLabel(respuesta);
            dialogoOk.visible();
        }
    }

    public void editar(Restaurante resta, int fila) {

        nombreTF.setText(resta.getNombre());
        ubicacionTF.setText(resta.getUbicacion());
        tipoTF.setText(resta.getTipo());
        horarioTF.setText(resta.getHorario());

        filaU = fila;
    }

    public void actualizar() {
        if (filaU != 0) {
            restaurante.setNombre(nombreTF.getText());
            restaurante.setUbicacion(ubicacionTF.getText());
            restaurante.setTipo(tipoTF.getText());
            restaurante.setHorario(horarioTF.getText());

            String respuesta = validar.validarRestaurante(restaurante);

            if ("Longitud nombre incorrecta".equals(respuesta)) {
                dialogoOk.textoLabel(respuesta);
                dialogoOk.visible();
            } else if ("Longitud ubicación incorrecta".equals(respuesta)) {
                dialogoOk.textoLabel(respuesta);
                dialogoOk.visible();
            } else if ("Longitud tipo incorrecta".equals(respuesta)) {
                dialogoOk.textoLabel(respuesta);
                dialogoOk.visible();
            } else if ("Longitud horario incorrecta".equals(respuesta)) {
                dialogoOk.textoLabel(respuesta);
                dialogoOk.visible();
            } else {
                daoRes.editar(restaurante.getNombre(), restaurante.getUbicacion(), restaurante.getTipo(), restaurante.getHorario(), filaU);
                vaciarCampos();
                dialogoOk.textoLabel(respuesta);
                dialogoOk.visible();
                filaU = 0;
            }
        } else {
            dialogoOk.textoLabel("Por favor vuelva atrás");
            dialogoOk.visible();
        }
    }

    public void nuevoVisible() {
        guardar.setVisible(true);
        editarNuevo.setVisible(false);
    }

    public void editarVisible() {
        guardar.setVisible(false);
        editarNuevo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ubicacionLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        horarioLabel = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        primerSeparador = new javax.swing.JSeparator();
        ubicacionTF = new javax.swing.JTextField();
        segundoSeparador = new javax.swing.JSeparator();
        tipoTF = new javax.swing.JTextField();
        tercerSeparador = new javax.swing.JSeparator();
        horarioTF = new javax.swing.JTextField();
        cuartoSeparador = new javax.swing.JSeparator();
        guardar = new javax.swing.JLabel();
        editarNuevo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(164, 186, 191));

        ubicacionLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        ubicacionLabel.setForeground(new java.awt.Color(36, 56, 63));
        ubicacionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ubicacionLabel.setText("Ubicación");

        nombreLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(36, 56, 63));
        nombreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreLabel.setText("Nombre");

        tipoLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        tipoLabel.setForeground(new java.awt.Color(36, 56, 63));
        tipoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tipoLabel.setText("Tipo");

        horarioLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        horarioLabel.setForeground(new java.awt.Color(36, 56, 63));
        horarioLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        horarioLabel.setText("Horario");

        nombreTF.setBackground(new java.awt.Color(164, 186, 191));
        nombreTF.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        nombreTF.setForeground(new java.awt.Color(36, 56, 63));
        nombreTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreTF.setBorder(null);
        nombreTF.setCaretColor(new java.awt.Color(36, 56, 63));
        nombreTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        primerSeparador.setBackground(new java.awt.Color(36, 56, 63));

        ubicacionTF.setBackground(new java.awt.Color(164, 186, 191));
        ubicacionTF.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        ubicacionTF.setForeground(new java.awt.Color(36, 56, 63));
        ubicacionTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ubicacionTF.setBorder(null);

        segundoSeparador.setBackground(new java.awt.Color(36, 56, 63));

        tipoTF.setBackground(new java.awt.Color(164, 186, 191));
        tipoTF.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        tipoTF.setForeground(new java.awt.Color(36, 56, 63));
        tipoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tipoTF.setBorder(null);

        tercerSeparador.setBackground(new java.awt.Color(36, 56, 63));

        horarioTF.setBackground(new java.awt.Color(164, 186, 191));
        horarioTF.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        horarioTF.setForeground(new java.awt.Color(36, 56, 63));
        horarioTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        horarioTF.setBorder(null);

        cuartoSeparador.setBackground(new java.awt.Color(36, 56, 63));

        guardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/clipboardM.png"))); // NOI18N
        guardar.setToolTipText("Guardar");
        guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });

        editarNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editarNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/test.png"))); // NOI18N
        editarNuevo.setToolTipText("Actualizar");
        editarNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarNuevoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(primerSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(350, 350, 350)
                        .addComponent(editarNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(ubicacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(ubicacionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(segundoSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(tipoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(tipoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(tercerSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(horarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(horarioTF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(cuartoSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(980, 980, 980)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editarNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(primerSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ubicacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubicacionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(segundoSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(tercerSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(horarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horarioTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(cuartoSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
        guardarDatos();
    }//GEN-LAST:event_guardarMouseClicked

    private void editarNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarNuevoMouseClicked
        actualizar();
    }//GEN-LAST:event_editarNuevoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator cuartoSeparador;
    private javax.swing.JLabel editarNuevo;
    private javax.swing.JLabel guardar;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JTextField horarioTF;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JSeparator primerSeparador;
    private javax.swing.JSeparator segundoSeparador;
    private javax.swing.JSeparator tercerSeparador;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JTextField tipoTF;
    private javax.swing.JLabel ubicacionLabel;
    private javax.swing.JTextField ubicacionTF;
    // End of variables declaration//GEN-END:variables
}
