package Frontera;

import Conexion.Conexion;
import Control.ValidarRestaurante;
import DAO.RestauranteDAO;
import Entidad.Restaurante;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class NuevoRestaurante extends javax.swing.JPanel {

    private Dialogo dialogo = new Dialogo(null, true);

    Conexion con = new Conexion();
    Connection Conectado = con.conectar("root", "17111996");

    private Restaurante restaurante = new Restaurante();
    private ValidarRestaurante validar = new ValidarRestaurante();
    private RestauranteDAO daoRes = new RestauranteDAO();

    private DialogoOK dialogoOk = new DialogoOK(null, true);

    public NuevoRestaurante() {
        initComponents();
    }

    public boolean validarCampos() {
        return (restauranteTF1.getText().isEmpty() && restauranteTF4.getText().isEmpty() && restauranteTF5.getText().isEmpty() && restauranteTF6.getText().isEmpty());
    }

    public void vaciarCampos() {
        restauranteTF1.setText("");
        restauranteTF4.setText("");
        restauranteTF5.setText("");
        restauranteTF6.setText("");
    }

    public void guardarDatos() {

        restaurante.setNombre(restauranteTF1.getText());
        restaurante.setUbicacion(restauranteTF4.getText());
        restaurante.setTipo(restauranteTF5.getText());
        restaurante.setHorario(restauranteTF6.getText());

        String respuesta = validar.validarRestaurante(restaurante);

        if ("Longitud nombre incorrecta".equals(respuesta)) {
            dialogoOk.textoLabel(respuesta);
            dialogoOk.visible();
        } else if ("Longitud ubicación incorrecta".equals(respuesta)) {
            dialogoOk.textoLabel(respuesta);
            dialogoOk.visible();
        } else if ("Longitud tipo incorrecta".equals(respuesta)) {
            dialogoOk.textoLabel(respuesta);
            dialogoOk.visible();
        } else if ("Longitud horario incorrecta".equals(respuesta)) {
            dialogoOk.textoLabel(respuesta);
            dialogoOk.visible();
        } else {
            daoRes.crear(restaurante.getNombre(), restauranteTF4.getText(), restauranteTF5.getText(), restauranteTF6.getText());
            vaciarCampos();
            dialogoOk.textoLabel(respuesta);
            dialogoOk.visible();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ubicacionLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        horarioLabel = new javax.swing.JLabel();
        restauranteTF1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        restauranteTF4 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        restauranteTF5 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        restauranteTF6 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(164, 186, 191));

        ubicacionLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        ubicacionLabel.setForeground(new java.awt.Color(36, 56, 63));
        ubicacionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ubicacionLabel.setText("Ubicación");

        nombreLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(36, 56, 63));
        nombreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreLabel.setText("Nombre");

        tipoLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        tipoLabel.setForeground(new java.awt.Color(36, 56, 63));
        tipoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tipoLabel.setText("Tipo");

        horarioLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        horarioLabel.setForeground(new java.awt.Color(36, 56, 63));
        horarioLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        horarioLabel.setText("Horario");

        restauranteTF1.setBackground(new java.awt.Color(164, 186, 191));
        restauranteTF1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        restauranteTF1.setForeground(new java.awt.Color(36, 56, 63));
        restauranteTF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        restauranteTF1.setBorder(null);
        restauranteTF1.setCaretColor(new java.awt.Color(36, 56, 63));
        restauranteTF1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator1.setBackground(new java.awt.Color(36, 56, 63));

        restauranteTF4.setBackground(new java.awt.Color(164, 186, 191));
        restauranteTF4.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        restauranteTF4.setForeground(new java.awt.Color(36, 56, 63));
        restauranteTF4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        restauranteTF4.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(36, 56, 63));

        restauranteTF5.setBackground(new java.awt.Color(164, 186, 191));
        restauranteTF5.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        restauranteTF5.setForeground(new java.awt.Color(36, 56, 63));
        restauranteTF5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        restauranteTF5.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(36, 56, 63));

        restauranteTF6.setBackground(new java.awt.Color(164, 186, 191));
        restauranteTF6.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        restauranteTF6.setForeground(new java.awt.Color(36, 56, 63));
        restauranteTF6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        restauranteTF6.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(36, 56, 63));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/diskette.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(restauranteTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(390, 390, 390)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(ubicacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(restauranteTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(390, 390, 390)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(tipoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(restauranteTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(390, 390, 390)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(horarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(restauranteTF6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(390, 390, 390)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 440, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restauranteTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ubicacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restauranteTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restauranteTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(horarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restauranteTF6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        guardarDatos();
    }//GEN-LAST:event_jLabel6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField restauranteTF1;
    private javax.swing.JTextField restauranteTF4;
    private javax.swing.JTextField restauranteTF5;
    private javax.swing.JTextField restauranteTF6;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JLabel ubicacionLabel;
    // End of variables declaration//GEN-END:variables
}
